server:
  # 1. 开启优雅停机
  shutdown: graceful
# actuator 监控配置
management:
  endpoint:
    shutdown:
      # 2. 启用actuator方式关机
      enabled: true
  endpoints:
    web:
      exposure:
        # 3. 必须暴露此接口, 才能调用 /actuator/shutdown
        include: shutdown
logging:
  file:
    # 测试 spring-boot-properties-migrator
    max-size: 10mb
spring:
  output:
    ansi:
      enabled: always
  security:
    user:
      password: 123456
  datasource:
    #  驱动
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名: test
    url: jdbc:h2:~/test
    username: sa
  h2:
    console:
      # 访问 /h2-console 打开h2控制台
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
demo:
  name: demo
